/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import com.elsevier.pure.api.sample.stubs.model.ClassificationRef;
import com.elsevier.pure.api.sample.stubs.model.CompoundDateRange;
import com.elsevier.pure.api.sample.stubs.model.OrganizationOrExternalOrganizationRef;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AcademicQualification
 */
public class AcademicQualificationTest {
    private final AcademicQualification model = new AcademicQualification();

    /**
     * Model tests for AcademicQualification
     */
    @Test
    public void testAcademicQualification() {
        // TODO: test AcademicQualification
    }

    /**
     * Test the property 'pureId'
     */
    @Test
    public void pureIdTest() {
        // TODO: test pureId
    }

    /**
     * Test the property 'awardDate'
     */
    @Test
    public void awardDateTest() {
        // TODO: test awardDate
    }

    /**
     * Test the property 'period'
     */
    @Test
    public void periodTest() {
        // TODO: test period
    }

    /**
     * Test the property 'fieldOfStudy'
     */
    @Test
    public void fieldOfStudyTest() {
        // TODO: test fieldOfStudy
    }

    /**
     * Test the property 'fieldOfStudyUnstructured'
     */
    @Test
    public void fieldOfStudyUnstructuredTest() {
        // TODO: test fieldOfStudyUnstructured
    }

    /**
     * Test the property 'organization'
     */
    @Test
    public void organizationTest() {
        // TODO: test organization
    }

    /**
     * Test the property 'projectTitle'
     */
    @Test
    public void projectTitleTest() {
        // TODO: test projectTitle
    }

    /**
     * Test the property 'qualification'
     */
    @Test
    public void qualificationTest() {
        // TODO: test qualification
    }

    /**
     * Test the property 'qualificationUnstructured'
     */
    @Test
    public void qualificationUnstructuredTest() {
        // TODO: test qualificationUnstructured
    }

}
