/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import com.elsevier.pure.api.sample.stubs.model.AccessDefinitionContentServiceFilter;
import com.elsevier.pure.api.sample.stubs.model.AccessDefinitionSystemNameFieldFilter;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccessDefinition
 */
public class AccessDefinitionTest {
    private final AccessDefinition model = new AccessDefinition();

    /**
     * Model tests for AccessDefinition
     */
    @Test
    public void testAccessDefinition() {
        // TODO: test AccessDefinition
    }

    /**
     * Test the property 'pureId'
     */
    @Test
    public void pureIdTest() {
        // TODO: test pureId
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'modifiedBy'
     */
    @Test
    public void modifiedByTest() {
        // TODO: test modifiedBy
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    public void modifiedDateTest() {
        // TODO: test modifiedDate
    }

    /**
     * Test the property 'portalUrl'
     */
    @Test
    public void portalUrlTest() {
        // TODO: test portalUrl
    }

    /**
     * Test the property 'prettyUrlIdentifiers'
     */
    @Test
    public void prettyUrlIdentifiersTest() {
        // TODO: test prettyUrlIdentifiers
    }

    /**
     * Test the property 'previousUuids'
     */
    @Test
    public void previousUuidsTest() {
        // TODO: test previousUuids
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'accessDefinitionFieldFilters'
     */
    @Test
    public void accessDefinitionFieldFiltersTest() {
        // TODO: test accessDefinitionFieldFilters
    }

    /**
     * Test the property 'accessDefinitionContentServiceFilter'
     */
    @Test
    public void accessDefinitionContentServiceFilterTest() {
        // TODO: test accessDefinitionContentServiceFilter
    }

    /**
     * Test the property 'systemName'
     */
    @Test
    public void systemNameTest() {
        // TODO: test systemName
    }

}
