/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccessDefinitionContentServiceFilter
 */
public class AccessDefinitionContentServiceFilterTest {
    private final AccessDefinitionContentServiceFilter model = new AccessDefinitionContentServiceFilter();

    /**
     * Model tests for AccessDefinitionContentServiceFilter
     */
    @Test
    public void testAccessDefinitionContentServiceFilter() {
        // TODO: test AccessDefinitionContentServiceFilter
    }

    /**
     * Test the property 'contentServiceFilterName'
     */
    @Test
    public void contentServiceFilterNameTest() {
        // TODO: test contentServiceFilterName
    }

}
