/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import com.elsevier.pure.api.sample.stubs.model.BookSeriesJournalAssociation;
import com.elsevier.pure.api.sample.stubs.model.ExternalOrganizationRef;
import com.elsevier.pure.api.sample.stubs.model.PublicationSeries;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContributionToMemorandumAllOf
 */
public class ContributionToMemorandumAllOfTest {
    private final ContributionToMemorandumAllOf model = new ContributionToMemorandumAllOf();

    /**
     * Model tests for ContributionToMemorandumAllOf
     */
    @Test
    public void testContributionToMemorandumAllOf() {
        // TODO: test ContributionToMemorandumAllOf
    }

    /**
     * Test the property 'applicant'
     */
    @Test
    public void applicantTest() {
        // TODO: test applicant
    }

    /**
     * Test the property 'projectNumber'
     */
    @Test
    public void projectNumberTest() {
        // TODO: test projectNumber
    }

    /**
     * Test the property 'journalNumber'
     */
    @Test
    public void journalNumberTest() {
        // TODO: test journalNumber
    }

    /**
     * Test the property 'dateFinished'
     */
    @Test
    public void dateFinishedTest() {
        // TODO: test dateFinished
    }

    /**
     * Test the property 'numberOfPages'
     */
    @Test
    public void numberOfPagesTest() {
        // TODO: test numberOfPages
    }

    /**
     * Test the property 'publicationSeries'
     */
    @Test
    public void publicationSeriesTest() {
        // TODO: test publicationSeries
    }

    /**
     * Test the property 'bookSeries'
     */
    @Test
    public void bookSeriesTest() {
        // TODO: test bookSeries
    }

}
