/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import com.elsevier.pure.api.sample.stubs.model.CaseNote;
import com.elsevier.pure.api.sample.stubs.model.ConferenceSeriesRef;
import com.elsevier.pure.api.sample.stubs.model.EventRef;
import com.elsevier.pure.api.sample.stubs.model.JournalAssociation;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContributionToJournalAllOf
 */
public class ContributionToJournalAllOfTest {
    private final ContributionToJournalAllOf model = new ContributionToJournalAllOf();

    /**
     * Model tests for ContributionToJournalAllOf
     */
    @Test
    public void testContributionToJournalAllOf() {
        // TODO: test ContributionToJournalAllOf
    }

    /**
     * Test the property 'event'
     */
    @Test
    public void eventTest() {
        // TODO: test event
    }

    /**
     * Test the property 'pages'
     */
    @Test
    public void pagesTest() {
        // TODO: test pages
    }

    /**
     * Test the property 'volume'
     */
    @Test
    public void volumeTest() {
        // TODO: test volume
    }

    /**
     * Test the property 'journalAssociation'
     */
    @Test
    public void journalAssociationTest() {
        // TODO: test journalAssociation
    }

    /**
     * Test the property 'articleNumber'
     */
    @Test
    public void articleNumberTest() {
        // TODO: test articleNumber
    }

    /**
     * Test the property 'journalNumber'
     */
    @Test
    public void journalNumberTest() {
        // TODO: test journalNumber
    }

    /**
     * Test the property 'caseNotes'
     */
    @Test
    public void caseNotesTest() {
        // TODO: test caseNotes
    }

    /**
     * Test the property 'conferenceSeries'
     */
    @Test
    public void conferenceSeriesTest() {
        // TODO: test conferenceSeries
    }

    /**
     * Test the property 'numberOfPages'
     */
    @Test
    public void numberOfPagesTest() {
        // TODO: test numberOfPages
    }

}
