/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import com.elsevier.pure.api.sample.stubs.model.ContentRef;
import com.elsevier.pure.api.sample.stubs.model.DisciplinesDisciplineAssignment;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DisciplinesAssociation
 */
public class DisciplinesAssociationTest {
    private final DisciplinesAssociation model = new DisciplinesAssociation();

    /**
     * Model tests for DisciplinesAssociation
     */
    @Test
    public void testDisciplinesAssociation() {
        // TODO: test DisciplinesAssociation
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'disciplineScheme'
     */
    @Test
    public void disciplineSchemeTest() {
        // TODO: test disciplineScheme
    }

    /**
     * Test the property 'disciplineAssignments'
     */
    @Test
    public void disciplineAssignmentsTest() {
        // TODO: test disciplineAssignments
    }

}
