/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import com.elsevier.pure.api.sample.stubs.model.AdditionalISSN;
import io.swagger.annotations.ApiModel;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ElectronicISSN
 */
public class ElectronicISSNTest {
    private final ElectronicISSN model = new ElectronicISSN();

    /**
     * Model tests for ElectronicISSN
     */
    @Test
    public void testElectronicISSN() {
        // TODO: test ElectronicISSN
    }

    /**
     * Test the property 'issn'
     */
    @Test
    public void issnTest() {
        // TODO: test issn
    }

    /**
     * Test the property 'typeDiscriminator'
     */
    @Test
    public void typeDiscriminatorTest() {
        // TODO: test typeDiscriminator
    }

}
