/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import org.junit.Test;


/**
 * Model tests for ExternalOrganization
 */
public class ExternalOrganizationTest {
    private final ExternalOrganization model = new ExternalOrganization();

    /**
     * Model tests for ExternalOrganization
     */
    @Test
    public void testExternalOrganization() {
        // TODO: test ExternalOrganization
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'modifiedBy'
     */
    @Test
    public void modifiedByTest() {
        // TODO: test modifiedBy
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    public void modifiedDateTest() {
        // TODO: test modifiedDate
    }

    /**
     * Test the property 'portalUrl'
     */
    @Test
    public void portalUrlTest() {
        // TODO: test portalUrl
    }

    /**
     * Test the property 'prettyUrlIdentifiers'
     */
    @Test
    public void prettyUrlIdentifiersTest() {
        // TODO: test prettyUrlIdentifiers
    }

    /**
     * Test the property 'previousUuids'
     */
    @Test
    public void previousUuidsTest() {
        // TODO: test previousUuids
    }

    /**
     * Test the property 'externallyManaged'
     */
    @Test
    public void externallyManagedTest() {
        // TODO: test externallyManaged
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'natureTypes'
     */
    @Test
    public void natureTypesTest() {
        // TODO: test natureTypes
    }

    /**
     * Test the property 'acronym'
     */
    @Test
    public void acronymTest() {
        // TODO: test acronym
    }

    /**
     * Test the property 'alternativeNames'
     */
    @Test
    public void alternativeNamesTest() {
        // TODO: test alternativeNames
    }

    /**
     * Test the property 'identifiers'
     */
    @Test
    public void identifiersTest() {
        // TODO: test identifiers
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'mobilePhoneNumber'
     */
    @Test
    public void mobilePhoneNumberTest() {
        // TODO: test mobilePhoneNumber
    }

    /**
     * Test the property 'fax'
     */
    @Test
    public void faxTest() {
        // TODO: test fax
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'bankAccountNumber'
     */
    @Test
    public void bankAccountNumberTest() {
        // TODO: test bankAccountNumber
    }

    /**
     * Test the property 'vatNumber'
     */
    @Test
    public void vatNumberTest() {
        // TODO: test vatNumber
    }

    /**
     * Test the property 'documents'
     */
    @Test
    public void documentsTest() {
        // TODO: test documents
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'keywordGroups'
     */
    @Test
    public void keywordGroupsTest() {
        // TODO: test keywordGroups
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'visibility'
     */
    @Test
    public void visibilityTest() {
        // TODO: test visibility
    }

    /**
     * Test the property 'workflow'
     */
    @Test
    public void workflowTest() {
        // TODO: test workflow
    }

    /**
     * Test the property 'family'
     */
    @Test
    public void familyTest() {
        // TODO: test family
    }

}
