/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import com.elsevier.pure.api.sample.stubs.model.ClassificationRef;
import com.elsevier.pure.api.sample.stubs.model.DateRange;
import com.elsevier.pure.api.sample.stubs.model.ElectronicVersion;
import com.elsevier.pure.api.sample.stubs.model.ElectronicVersionFile;
import com.elsevier.pure.api.sample.stubs.model.FileElectronicVersionAllOf;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FileElectronicVersion
 */
public class FileElectronicVersionTest {
    private final FileElectronicVersion model = new FileElectronicVersion();

    /**
     * Model tests for FileElectronicVersion
     */
    @Test
    public void testFileElectronicVersion() {
        // TODO: test FileElectronicVersion
    }

    /**
     * Test the property 'pureId'
     */
    @Test
    public void pureIdTest() {
        // TODO: test pureId
    }

    /**
     * Test the property 'accessType'
     */
    @Test
    public void accessTypeTest() {
        // TODO: test accessType
    }

    /**
     * Test the property 'embargoPeriod'
     */
    @Test
    public void embargoPeriodTest() {
        // TODO: test embargoPeriod
    }

    /**
     * Test the property 'licenseType'
     */
    @Test
    public void licenseTypeTest() {
        // TODO: test licenseType
    }

    /**
     * Test the property 'userDefinedLicense'
     */
    @Test
    public void userDefinedLicenseTest() {
        // TODO: test userDefinedLicense
    }

    /**
     * Test the property 'visibleOnPortalDate'
     */
    @Test
    public void visibleOnPortalDateTest() {
        // TODO: test visibleOnPortalDate
    }

    /**
     * Test the property 'creator'
     */
    @Test
    public void creatorTest() {
        // TODO: test creator
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'typeDiscriminator'
     */
    @Test
    public void typeDiscriminatorTest() {
        // TODO: test typeDiscriminator
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'rightsStatement'
     */
    @Test
    public void rightsStatementTest() {
        // TODO: test rightsStatement
    }

    /**
     * Test the property 'file'
     */
    @Test
    public void fileTest() {
        // TODO: test file
    }

    /**
     * Test the property 'versionType'
     */
    @Test
    public void versionTypeTest() {
        // TODO: test versionType
    }

}
