/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import com.elsevier.pure.api.sample.stubs.model.AdditionalISSN;
import com.elsevier.pure.api.sample.stubs.model.ClassificationRef;
import com.elsevier.pure.api.sample.stubs.model.ISSN;
import com.elsevier.pure.api.sample.stubs.model.Identifier;
import com.elsevier.pure.api.sample.stubs.model.JournalTitle;
import com.elsevier.pure.api.sample.stubs.model.KeywordGroup;
import com.elsevier.pure.api.sample.stubs.model.Link;
import com.elsevier.pure.api.sample.stubs.model.PublisherRef;
import com.elsevier.pure.api.sample.stubs.model.Workflow;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Journal
 */
public class JournalTest {
    private final Journal model = new Journal();

    /**
     * Model tests for Journal
     */
    @Test
    public void testJournal() {
        // TODO: test Journal
    }

    /**
     * Test the property 'pureId'
     */
    @Test
    public void pureIdTest() {
        // TODO: test pureId
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'modifiedBy'
     */
    @Test
    public void modifiedByTest() {
        // TODO: test modifiedBy
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    public void modifiedDateTest() {
        // TODO: test modifiedDate
    }

    /**
     * Test the property 'portalUrl'
     */
    @Test
    public void portalUrlTest() {
        // TODO: test portalUrl
    }

    /**
     * Test the property 'prettyUrlIdentifiers'
     */
    @Test
    public void prettyUrlIdentifiersTest() {
        // TODO: test prettyUrlIdentifiers
    }

    /**
     * Test the property 'previousUuids'
     */
    @Test
    public void previousUuidsTest() {
        // TODO: test previousUuids
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'issns'
     */
    @Test
    public void issnsTest() {
        // TODO: test issns
    }

    /**
     * Test the property 'additionalSearchableIssns'
     */
    @Test
    public void additionalSearchableIssnsTest() {
        // TODO: test additionalSearchableIssns
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'indexedInDoaj'
     */
    @Test
    public void indexedInDoajTest() {
        // TODO: test indexedInDoaj
    }

    /**
     * Test the property 'keywordGroups'
     */
    @Test
    public void keywordGroupsTest() {
        // TODO: test keywordGroups
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'publisher'
     */
    @Test
    public void publisherTest() {
        // TODO: test publisher
    }

    /**
     * Test the property 'identifiers'
     */
    @Test
    public void identifiersTest() {
        // TODO: test identifiers
    }

    /**
     * Test the property 'titles'
     */
    @Test
    public void titlesTest() {
        // TODO: test titles
    }

    /**
     * Test the property 'additionalSearchableTitles'
     */
    @Test
    public void additionalSearchableTitlesTest() {
        // TODO: test additionalSearchableTitles
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'workflow'
     */
    @Test
    public void workflowTest() {
        // TODO: test workflow
    }

    /**
     * Test the property 'systemName'
     */
    @Test
    public void systemNameTest() {
        // TODO: test systemName
    }

}
