/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import org.junit.Test;


/**
 * Model tests for KeywordGroup
 */
public class KeywordGroupTest {
    private final KeywordGroup model = new KeywordGroup();

    /**
     * Model tests for KeywordGroup
     */
    @Test
    public void testKeywordGroup() {
        // TODO: test KeywordGroup
    }

    /**
     * Test the property 'pureId'
     */
    @Test
    public void pureIdTest() {
        // TODO: test pureId
    }

    /**
     * Test the property 'kgType'
     */
    @Test
    public void kgTypeTest() {
        // TODO: test kgType
    }

    /**
     * Test the property 'logicalName'
     */
    @Test
    public void logicalNameTest() {
        // TODO: test logicalName
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
