/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import com.elsevier.pure.api.sample.stubs.model.ClassificationRef;
import com.elsevier.pure.api.sample.stubs.model.ResearchOutputPeerReviewConfigurationCombination;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ResearchOutputPeerReviewConfiguration
 */
public class ResearchOutputPeerReviewConfigurationTest {
    private final ResearchOutputPeerReviewConfiguration model = new ResearchOutputPeerReviewConfiguration();

    /**
     * Model tests for ResearchOutputPeerReviewConfiguration
     */
    @Test
    public void testResearchOutputPeerReviewConfiguration() {
        // TODO: test ResearchOutputPeerReviewConfiguration
    }

    /**
     * Test the property 'researchOutputType'
     */
    @Test
    public void researchOutputTypeTest() {
        // TODO: test researchOutputType
    }

    /**
     * Test the property 'allowedCombinations'
     */
    @Test
    public void allowedCombinationsTest() {
        // TODO: test allowedCombinations
    }

}
