/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import com.elsevier.pure.api.sample.stubs.model.ClassificationRef;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for StaffOrganizationAssociationAllOf
 */
public class StaffOrganizationAssociationAllOfTest {
    private final StaffOrganizationAssociationAllOf model = new StaffOrganizationAssociationAllOf();

    /**
     * Model tests for StaffOrganizationAssociationAllOf
     */
    @Test
    public void testStaffOrganizationAssociationAllOf() {
        // TODO: test StaffOrganizationAssociationAllOf
    }

    /**
     * Test the property 'contractType'
     */
    @Test
    public void contractTypeTest() {
        // TODO: test contractType
    }

    /**
     * Test the property 'fte'
     */
    @Test
    public void fteTest() {
        // TODO: test fte
    }

    /**
     * Test the property 'jobDescription'
     */
    @Test
    public void jobDescriptionTest() {
        // TODO: test jobDescription
    }

    /**
     * Test the property 'jobTitle'
     */
    @Test
    public void jobTitleTest() {
        // TODO: test jobTitle
    }

    /**
     * Test the property 'staffType'
     */
    @Test
    public void staffTypeTest() {
        // TODO: test staffType
    }

}
