/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import com.elsevier.pure.api.sample.stubs.model.BookSeriesJournalAssociation;
import com.elsevier.pure.api.sample.stubs.model.PublicationSeries;
import com.elsevier.pure.api.sample.stubs.model.PublisherRef;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WorkingPaperAllOf
 */
public class WorkingPaperAllOfTest {
    private final WorkingPaperAllOf model = new WorkingPaperAllOf();

    /**
     * Model tests for WorkingPaperAllOf
     */
    @Test
    public void testWorkingPaperAllOf() {
        // TODO: test WorkingPaperAllOf
    }

    /**
     * Test the property 'volume'
     */
    @Test
    public void volumeTest() {
        // TODO: test volume
    }

    /**
     * Test the property 'numberOfPages'
     */
    @Test
    public void numberOfPagesTest() {
        // TODO: test numberOfPages
    }

    /**
     * Test the property 'pages'
     */
    @Test
    public void pagesTest() {
        // TODO: test pages
    }

    /**
     * Test the property 'publicationSeries'
     */
    @Test
    public void publicationSeriesTest() {
        // TODO: test publicationSeries
    }

    /**
     * Test the property 'placeOfPublication'
     */
    @Test
    public void placeOfPublicationTest() {
        // TODO: test placeOfPublication
    }

    /**
     * Test the property 'edition'
     */
    @Test
    public void editionTest() {
        // TODO: test edition
    }

    /**
     * Test the property 'printISBNs'
     */
    @Test
    public void printISBNsTest() {
        // TODO: test printISBNs
    }

    /**
     * Test the property 'electronicISBNs'
     */
    @Test
    public void electronicISBNsTest() {
        // TODO: test electronicISBNs
    }

    /**
     * Test the property 'publisher'
     */
    @Test
    public void publisherTest() {
        // TODO: test publisher
    }

    /**
     * Test the property 'bookSeries'
     */
    @Test
    public void bookSeriesTest() {
        // TODO: test bookSeries
    }

}
