/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import java.util.Objects;
import java.util.Arrays;
import com.elsevier.pure.api.sample.stubs.model.ClassificationRef;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A physical address
 */
@ApiModel(description = "A physical address")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-21T09:12:55.713+02:00[Europe/Copenhagen]")
public class Address {
  public static final String SERIALIZED_NAME_ROAD = "road";
  @SerializedName(SERIALIZED_NAME_ROAD)
  private String road;

  public static final String SERIALIZED_NAME_ROOM = "room";
  @SerializedName(SERIALIZED_NAME_ROOM)
  private String room;

  public static final String SERIALIZED_NAME_BUILDING = "building";
  @SerializedName(SERIALIZED_NAME_BUILDING)
  private String building;

  public static final String SERIALIZED_NAME_POSTAL_CODE = "postalCode";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE)
  private String postalCode;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private ClassificationRef country;


  public Address road(String road) {
    
    this.road = road;
    return this;
  }

   /**
   * Name of road and house number, eg. &#39;Pennsylvania Avenue&#39; or &#39;123 Main St.&#39;
   * @return road
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of road and house number, eg. 'Pennsylvania Avenue' or '123 Main St.'")

  public String getRoad() {
    return road;
  }


  public void setRoad(String road) {
    this.road = road;
  }


  public Address room(String room) {
    
    this.room = room;
    return this;
  }

   /**
   * Room number or name if available, eg. &#39;1.23&#39; or &#39;Office of Creative Services&#39;
   * @return room
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Room number or name if available, eg. '1.23' or 'Office of Creative Services'")

  public String getRoom() {
    return room;
  }


  public void setRoom(String room) {
    this.room = room;
  }


  public Address building(String building) {
    
    this.building = building;
    return this;
  }

   /**
   * Building Name if available, eg. &#39;Couper Administration Building&#39;
   * @return building
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Building Name if available, eg. 'Couper Administration Building'")

  public String getBuilding() {
    return building;
  }


  public void setBuilding(String building) {
    this.building = building;
  }


  public Address postalCode(String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Postal code
   * @return postalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Postal code")

  public String getPostalCode() {
    return postalCode;
  }


  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public Address city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * City or town, eg. &#39;Binghamton&#39;
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "City or town, eg. 'Binghamton'")

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  public Address country(ClassificationRef country) {
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ClassificationRef getCountry() {
    return country;
  }


  public void setCountry(ClassificationRef country) {
    this.country = country;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Address address = (Address) o;
    return Objects.equals(this.road, address.road) &&
        Objects.equals(this.room, address.room) &&
        Objects.equals(this.building, address.building) &&
        Objects.equals(this.postalCode, address.postalCode) &&
        Objects.equals(this.city, address.city) &&
        Objects.equals(this.country, address.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(road, room, building, postalCode, city, country);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Address {\n");
    sb.append("    road: ").append(toIndentedString(road)).append("\n");
    sb.append("    room: ").append(toIndentedString(room)).append("\n");
    sb.append("    building: ").append(toIndentedString(building)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

