/*
 * Pure API
 * Description text
 *
 * The version of the OpenAPI document: 0.1-Alpha
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import java.util.Objects;
import java.util.Arrays;
import com.elsevier.pure.api.sample.stubs.model.ClassificationRef;
import com.elsevier.pure.api.sample.stubs.model.Id;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Relation between classifications
 */
@ApiModel(description = "Relation between classifications")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-06T09:45:25.329746+01:00[Europe/Copenhagen]")
public class ClassificationRelation {
  public static final String SERIALIZED_NAME_PURE_ID = "pureId";
  @SerializedName(SERIALIZED_NAME_PURE_ID)
  private Long pureId;

  public static final String SERIALIZED_NAME_FREE_FORM_EXTERNAL_IDS = "freeFormExternalIds";
  @SerializedName(SERIALIZED_NAME_FREE_FORM_EXTERNAL_IDS)
  private List<Id> freeFormExternalIds = null;

  public static final String SERIALIZED_NAME_EXTERNALLY_MANAGED = "externallyManaged";
  @SerializedName(SERIALIZED_NAME_EXTERNALLY_MANAGED)
  private Boolean externallyManaged;

  public static final String SERIALIZED_NAME_RELATED_TO = "relatedTo";
  @SerializedName(SERIALIZED_NAME_RELATED_TO)
  private ClassificationRef relatedTo;

  public static final String SERIALIZED_NAME_RELATION_TYPE = "relationType";
  @SerializedName(SERIALIZED_NAME_RELATION_TYPE)
  private ClassificationRef relationType;


   /**
   * Pure database ID of the object
   * @return pureId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Pure database ID of the object")

  public Long getPureId() {
    return pureId;
  }




  public ClassificationRelation freeFormExternalIds(List<Id> freeFormExternalIds) {
    
    this.freeFormExternalIds = freeFormExternalIds;
    return this;
  }

  public ClassificationRelation addFreeFormExternalIdsItem(Id freeFormExternalIdsItem) {
    if (this.freeFormExternalIds == null) {
      this.freeFormExternalIds = new ArrayList<Id>();
    }
    this.freeFormExternalIds.add(freeFormExternalIdsItem);
    return this;
  }

   /**
   * IDs from the external sources (part of) the object was imported from
   * @return freeFormExternalIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "IDs from the external sources (part of) the object was imported from")

  public List<Id> getFreeFormExternalIds() {
    return freeFormExternalIds;
  }


  public void setFreeFormExternalIds(List<Id> freeFormExternalIds) {
    this.freeFormExternalIds = freeFormExternalIds;
  }


  public ClassificationRelation externallyManaged(Boolean externallyManaged) {
    
    this.externallyManaged = externallyManaged;
    return this;
  }

   /**
   * Signals that the information is maintained by synchronization from an external system
   * @return externallyManaged
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Signals that the information is maintained by synchronization from an external system")

  public Boolean getExternallyManaged() {
    return externallyManaged;
  }


  public void setExternallyManaged(Boolean externallyManaged) {
    this.externallyManaged = externallyManaged;
  }


  public ClassificationRelation relatedTo(ClassificationRef relatedTo) {
    
    this.relatedTo = relatedTo;
    return this;
  }

   /**
   * Get relatedTo
   * @return relatedTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ClassificationRef getRelatedTo() {
    return relatedTo;
  }


  public void setRelatedTo(ClassificationRef relatedTo) {
    this.relatedTo = relatedTo;
  }


  public ClassificationRelation relationType(ClassificationRef relationType) {
    
    this.relationType = relationType;
    return this;
  }

   /**
   * Get relationType
   * @return relationType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ClassificationRef getRelationType() {
    return relationType;
  }


  public void setRelationType(ClassificationRef relationType) {
    this.relationType = relationType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassificationRelation classificationRelation = (ClassificationRelation) o;
    return Objects.equals(this.pureId, classificationRelation.pureId) &&
        Objects.equals(this.freeFormExternalIds, classificationRelation.freeFormExternalIds) &&
        Objects.equals(this.externallyManaged, classificationRelation.externallyManaged) &&
        Objects.equals(this.relatedTo, classificationRelation.relatedTo) &&
        Objects.equals(this.relationType, classificationRelation.relationType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pureId, freeFormExternalIds, externallyManaged, relatedTo, relationType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassificationRelation {\n");
    sb.append("    pureId: ").append(toIndentedString(pureId)).append("\n");
    sb.append("    freeFormExternalIds: ").append(toIndentedString(freeFormExternalIds)).append("\n");
    sb.append("    externallyManaged: ").append(toIndentedString(externallyManaged)).append("\n");
    sb.append("    relatedTo: ").append(toIndentedString(relatedTo)).append("\n");
    sb.append("    relationType: ").append(toIndentedString(relationType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

