/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import java.util.Objects;
import java.util.Arrays;
import com.elsevier.pure.api.sample.stubs.model.ClassificationRef;
import com.elsevier.pure.api.sample.stubs.model.UploadedFile;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A classified file
 */
@ApiModel(description = "A classified file")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-28T22:49:29.739+02:00[Europe/Copenhagen]")
public class ClassifiedFile {
  public static final String SERIALIZED_NAME_PURE_ID = "pureId";
  @SerializedName(SERIALIZED_NAME_PURE_ID)
  private Long pureId;

  public static final String SERIALIZED_NAME_FILE_ID = "fileId";
  @SerializedName(SERIALIZED_NAME_FILE_ID)
  private String fileId;

  public static final String SERIALIZED_NAME_FILE_NAME = "fileName";
  @SerializedName(SERIALIZED_NAME_FILE_NAME)
  private String fileName;

  public static final String SERIALIZED_NAME_MIME_TYPE = "mimeType";
  @SerializedName(SERIALIZED_NAME_MIME_TYPE)
  private String mimeType;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  private Long size;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_UPLOADED_FILE = "uploadedFile";
  @SerializedName(SERIALIZED_NAME_UPLOADED_FILE)
  private UploadedFile uploadedFile;

  public static final String SERIALIZED_NAME_FILE_DATA = "fileData";
  @SerializedName(SERIALIZED_NAME_FILE_DATA)
  private byte[] fileData;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private ClassificationRef type;


   /**
   * Pure database ID of the object, prefer using the UUID if it is present on the entity
   * @return pureId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Pure database ID of the object, prefer using the UUID if it is present on the entity")

  public Long getPureId() {
    return pureId;
  }




   /**
   * The id of the file
   * @return fileId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The id of the file")

  public String getFileId() {
    return fileId;
  }




  public ClassifiedFile fileName(String fileName) {
    
    this.fileName = fileName;
    return this;
  }

   /**
   * The documents file name
   * @return fileName
  **/
  @ApiModelProperty(required = true, value = "The documents file name")

  public String getFileName() {
    return fileName;
  }


  public void setFileName(String fileName) {
    this.fileName = fileName;
  }


  public ClassifiedFile mimeType(String mimeType) {
    
    this.mimeType = mimeType;
    return this;
  }

   /**
   * The documents mime type
   * @return mimeType
  **/
  @ApiModelProperty(required = true, value = "The documents mime type")

  public String getMimeType() {
    return mimeType;
  }


  public void setMimeType(String mimeType) {
    this.mimeType = mimeType;
  }


  public ClassifiedFile size(Long size) {
    
    this.size = size;
    return this;
  }

   /**
   * The documents size in bytes
   * @return size
  **/
  @ApiModelProperty(required = true, value = "The documents size in bytes")

  public Long getSize() {
    return size;
  }


  public void setSize(Long size) {
    this.size = size;
  }


   /**
   * Download url for the binary file
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Download url for the binary file")

  public String getUrl() {
    return url;
  }




  public ClassifiedFile uploadedFile(UploadedFile uploadedFile) {
    
    this.uploadedFile = uploadedFile;
    return this;
  }

   /**
   * Get uploadedFile
   * @return uploadedFile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UploadedFile getUploadedFile() {
    return uploadedFile;
  }


  public void setUploadedFile(UploadedFile uploadedFile) {
    this.uploadedFile = uploadedFile;
  }


  public ClassifiedFile fileData(byte[] fileData) {
    
    this.fileData = fileData;
    return this;
  }

   /**
   * Base64 encoded file data for new files. This property can be used instead of uploadedFile for small files
   * @return fileData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Base64 encoded file data for new files. This property can be used instead of uploadedFile for small files")

  public byte[] getFileData() {
    return fileData;
  }


  public void setFileData(byte[] fileData) {
    this.fileData = fileData;
  }


  public ClassifiedFile type(ClassificationRef type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ClassificationRef getType() {
    return type;
  }


  public void setType(ClassificationRef type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassifiedFile classifiedFile = (ClassifiedFile) o;
    return Objects.equals(this.pureId, classifiedFile.pureId) &&
        Objects.equals(this.fileId, classifiedFile.fileId) &&
        Objects.equals(this.fileName, classifiedFile.fileName) &&
        Objects.equals(this.mimeType, classifiedFile.mimeType) &&
        Objects.equals(this.size, classifiedFile.size) &&
        Objects.equals(this.url, classifiedFile.url) &&
        Objects.equals(this.uploadedFile, classifiedFile.uploadedFile) &&
        Arrays.equals(this.fileData, classifiedFile.fileData) &&
        Objects.equals(this.type, classifiedFile.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pureId, fileId, fileName, mimeType, size, url, uploadedFile, Arrays.hashCode(fileData), type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassifiedFile {\n");
    sb.append("    pureId: ").append(toIndentedString(pureId)).append("\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    uploadedFile: ").append(toIndentedString(uploadedFile)).append("\n");
    sb.append("    fileData: ").append(toIndentedString(fileData)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

