/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A discipline scheme
 */
@ApiModel(description = "A discipline scheme")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-11T16:14:00.558+01:00[Europe/Copenhagen]")
public class DisciplinesDisciplineScheme {
  public static final String SERIALIZED_NAME_DISCIPLINE_SCHEME = "disciplineScheme";
  @SerializedName(SERIALIZED_NAME_DISCIPLINE_SCHEME)
  private String disciplineScheme;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;


  public DisciplinesDisciplineScheme disciplineScheme(String disciplineScheme) {
    
    this.disciplineScheme = disciplineScheme;
    return this;
  }

   /**
   * The discipline scheme identifier
   * @return disciplineScheme
  **/
  @ApiModelProperty(required = true, value = "The discipline scheme identifier")

  public String getDisciplineScheme() {
    return disciplineScheme;
  }


  public void setDisciplineScheme(String disciplineScheme) {
    this.disciplineScheme = disciplineScheme;
  }


  public DisciplinesDisciplineScheme title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * The discipline title
   * @return title
  **/
  @ApiModelProperty(required = true, value = "The discipline title")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DisciplinesDisciplineScheme disciplinesDisciplineScheme = (DisciplinesDisciplineScheme) o;
    return Objects.equals(this.disciplineScheme, disciplinesDisciplineScheme.disciplineScheme) &&
        Objects.equals(this.title, disciplinesDisciplineScheme.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disciplineScheme, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DisciplinesDisciplineScheme {\n");
    sb.append("    disciplineScheme: ").append(toIndentedString(disciplineScheme)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

