/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import java.util.Objects;
import java.util.Arrays;
import com.elsevier.pure.api.sample.stubs.model.ClassificationRef;
import com.elsevier.pure.api.sample.stubs.model.DateRange;
import com.elsevier.pure.api.sample.stubs.model.EventRef;
import com.elsevier.pure.api.sample.stubs.model.GeoLocation;
import com.elsevier.pure.api.sample.stubs.model.Identifier;
import com.elsevier.pure.api.sample.stubs.model.KeywordGroup;
import com.elsevier.pure.api.sample.stubs.model.Link;
import com.elsevier.pure.api.sample.stubs.model.OrganizationOrExternalOrganizationRef;
import com.elsevier.pure.api.sample.stubs.model.Workflow;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * An event typically a conference, workshop or similar
 */
@ApiModel(description = "An event typically a conference, workshop or similar")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-11T16:14:00.558+01:00[Europe/Copenhagen]")
public class Event {
  public static final String SERIALIZED_NAME_PURE_ID = "pureId";
  @SerializedName(SERIALIZED_NAME_PURE_ID)
  private Long pureId;

  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private UUID uuid;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private String createdBy;

  public static final String SERIALIZED_NAME_CREATED_DATE = "createdDate";
  @SerializedName(SERIALIZED_NAME_CREATED_DATE)
  private OffsetDateTime createdDate;

  public static final String SERIALIZED_NAME_MODIFIED_BY = "modifiedBy";
  @SerializedName(SERIALIZED_NAME_MODIFIED_BY)
  private String modifiedBy;

  public static final String SERIALIZED_NAME_MODIFIED_DATE = "modifiedDate";
  @SerializedName(SERIALIZED_NAME_MODIFIED_DATE)
  private OffsetDateTime modifiedDate;

  public static final String SERIALIZED_NAME_PORTAL_URL = "portalUrl";
  @SerializedName(SERIALIZED_NAME_PORTAL_URL)
  private String portalUrl;

  public static final String SERIALIZED_NAME_PRETTY_URL_IDENTIFIERS = "prettyUrlIdentifiers";
  @SerializedName(SERIALIZED_NAME_PRETTY_URL_IDENTIFIERS)
  private List<String> prettyUrlIdentifiers = null;

  public static final String SERIALIZED_NAME_PREVIOUS_UUIDS = "previousUuids";
  @SerializedName(SERIALIZED_NAME_PREVIOUS_UUIDS)
  private List<String> previousUuids = null;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private ClassificationRef type;

  public static final String SERIALIZED_NAME_ABBREVIATED_TITLE = "abbreviatedTitle";
  @SerializedName(SERIALIZED_NAME_ABBREVIATED_TITLE)
  private Map<String, String> abbreviatedTitle = null;

  public static final String SERIALIZED_NAME_GEO_LOCATION = "geoLocation";
  @SerializedName(SERIALIZED_NAME_GEO_LOCATION)
  private GeoLocation geoLocation;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_CONFERENCE_NUMBER = "conferenceNumber";
  @SerializedName(SERIALIZED_NAME_CONFERENCE_NUMBER)
  private String conferenceNumber;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private ClassificationRef country;

  public static final String SERIALIZED_NAME_DEGREE_OF_RECOGNITION = "degreeOfRecognition";
  @SerializedName(SERIALIZED_NAME_DEGREE_OF_RECOGNITION)
  private ClassificationRef degreeOfRecognition;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private Map<String, String> description = null;

  public static final String SERIALIZED_NAME_KEYWORD_GROUPS = "keywordGroups";
  @SerializedName(SERIALIZED_NAME_KEYWORD_GROUPS)
  private List<KeywordGroup> keywordGroups = null;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private List<Link> links = null;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private String location;

  public static final String SERIALIZED_NAME_ORGANIZERS = "organizers";
  @SerializedName(SERIALIZED_NAME_ORGANIZERS)
  private List<OrganizationOrExternalOrganizationRef> organizers = null;

  public static final String SERIALIZED_NAME_LIFECYCLE = "lifecycle";
  @SerializedName(SERIALIZED_NAME_LIFECYCLE)
  private DateRange lifecycle;

  public static final String SERIALIZED_NAME_EVENTS = "events";
  @SerializedName(SERIALIZED_NAME_EVENTS)
  private List<EventRef> events = null;

  public static final String SERIALIZED_NAME_IDENTIFIERS = "identifiers";
  @SerializedName(SERIALIZED_NAME_IDENTIFIERS)
  private List<Identifier> identifiers = null;

  public static final String SERIALIZED_NAME_SPONSOR_ORGANIZATIONS = "sponsorOrganizations";
  @SerializedName(SERIALIZED_NAME_SPONSOR_ORGANIZATIONS)
  private List<OrganizationOrExternalOrganizationRef> sponsorOrganizations = null;

  public static final String SERIALIZED_NAME_SUBDIVISION = "subdivision";
  @SerializedName(SERIALIZED_NAME_SUBDIVISION)
  private ClassificationRef subdivision;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private Map<String, String> title = null;

  public static final String SERIALIZED_NAME_SUB_TITLE = "subTitle";
  @SerializedName(SERIALIZED_NAME_SUB_TITLE)
  private Map<String, String> subTitle = null;

  public static final String SERIALIZED_NAME_WORKFLOW = "workflow";
  @SerializedName(SERIALIZED_NAME_WORKFLOW)
  private Workflow workflow;

  public static final String SERIALIZED_NAME_SYSTEM_NAME = "systemName";
  @SerializedName(SERIALIZED_NAME_SYSTEM_NAME)
  private String systemName;


   /**
   * Pure database ID of the object, prefer using the UUID if it is present on the entity
   * @return pureId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Pure database ID of the object, prefer using the UUID if it is present on the entity")

  public Long getPureId() {
    return pureId;
  }




   /**
   * UUID, this is the primary identity of the entity
   * @return uuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UUID, this is the primary identity of the entity")

  public UUID getUuid() {
    return uuid;
  }




   /**
   * Username of creator
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Username of creator")

  public String getCreatedBy() {
    return createdBy;
  }




   /**
   * Date and time of creation
   * @return createdDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date and time of creation")

  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }




   /**
   * Username of the user that performed a modification
   * @return modifiedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Username of the user that performed a modification")

  public String getModifiedBy() {
    return modifiedBy;
  }




   /**
   * Date and time of last modification
   * @return modifiedDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date and time of last modification")

  public OffsetDateTime getModifiedDate() {
    return modifiedDate;
  }




   /**
   * URL of the content on the Pure Portal
   * @return portalUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "URL of the content on the Pure Portal")

  public String getPortalUrl() {
    return portalUrl;
  }




   /**
   * All pretty URLs
   * @return prettyUrlIdentifiers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "All pretty URLs")

  public List<String> getPrettyUrlIdentifiers() {
    return prettyUrlIdentifiers;
  }




   /**
   * UUIDs of other content items which have been merged into this content item (or similar)
   * @return previousUuids
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UUIDs of other content items which have been merged into this content item (or similar)")

  public List<String> getPreviousUuids() {
    return previousUuids;
  }




  public Event version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * A hash representing the current version of the content. For new content this is null, and for existing content the current value. The property should never be modified explicitly by a client.
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A hash representing the current version of the content. For new content this is null, and for existing content the current value. The property should never be modified explicitly by a client.")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public Event type(ClassificationRef type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ClassificationRef getType() {
    return type;
  }


  public void setType(ClassificationRef type) {
    this.type = type;
  }


  public Event abbreviatedTitle(Map<String, String> abbreviatedTitle) {
    
    this.abbreviatedTitle = abbreviatedTitle;
    return this;
  }

  public Event putAbbreviatedTitleItem(String key, String abbreviatedTitleItem) {
    if (this.abbreviatedTitle == null) {
      this.abbreviatedTitle = new HashMap<String, String>();
    }
    this.abbreviatedTitle.put(key, abbreviatedTitleItem);
    return this;
  }

   /**
   * A set of potentially formatted string values each localized for a specific submission locale. Please note that invalid locale values will be ignored.
   * @return abbreviatedTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"en_GB\":\"Some text\"}", value = "A set of potentially formatted string values each localized for a specific submission locale. Please note that invalid locale values will be ignored.")

  public Map<String, String> getAbbreviatedTitle() {
    return abbreviatedTitle;
  }


  public void setAbbreviatedTitle(Map<String, String> abbreviatedTitle) {
    this.abbreviatedTitle = abbreviatedTitle;
  }


  public Event geoLocation(GeoLocation geoLocation) {
    
    this.geoLocation = geoLocation;
    return this;
  }

   /**
   * Get geoLocation
   * @return geoLocation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GeoLocation getGeoLocation() {
    return geoLocation;
  }


  public void setGeoLocation(GeoLocation geoLocation) {
    this.geoLocation = geoLocation;
  }


  public Event city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * The city of the event
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The city of the event")

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  public Event conferenceNumber(String conferenceNumber) {
    
    this.conferenceNumber = conferenceNumber;
    return this;
  }

   /**
   * The conference number of the event
   * @return conferenceNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The conference number of the event")

  public String getConferenceNumber() {
    return conferenceNumber;
  }


  public void setConferenceNumber(String conferenceNumber) {
    this.conferenceNumber = conferenceNumber;
  }


  public Event country(ClassificationRef country) {
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ClassificationRef getCountry() {
    return country;
  }


  public void setCountry(ClassificationRef country) {
    this.country = country;
  }


  public Event degreeOfRecognition(ClassificationRef degreeOfRecognition) {
    
    this.degreeOfRecognition = degreeOfRecognition;
    return this;
  }

   /**
   * Get degreeOfRecognition
   * @return degreeOfRecognition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ClassificationRef getDegreeOfRecognition() {
    return degreeOfRecognition;
  }


  public void setDegreeOfRecognition(ClassificationRef degreeOfRecognition) {
    this.degreeOfRecognition = degreeOfRecognition;
  }


  public Event description(Map<String, String> description) {
    
    this.description = description;
    return this;
  }

  public Event putDescriptionItem(String key, String descriptionItem) {
    if (this.description == null) {
      this.description = new HashMap<String, String>();
    }
    this.description.put(key, descriptionItem);
    return this;
  }

   /**
   * A set of potentially formatted string values each localized for a specific submission locale. Please note that invalid locale values will be ignored.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"en_GB\":\"Some text\"}", value = "A set of potentially formatted string values each localized for a specific submission locale. Please note that invalid locale values will be ignored.")

  public Map<String, String> getDescription() {
    return description;
  }


  public void setDescription(Map<String, String> description) {
    this.description = description;
  }


  public Event keywordGroups(List<KeywordGroup> keywordGroups) {
    
    this.keywordGroups = keywordGroups;
    return this;
  }

  public Event addKeywordGroupsItem(KeywordGroup keywordGroupsItem) {
    if (this.keywordGroups == null) {
      this.keywordGroups = new ArrayList<KeywordGroup>();
    }
    this.keywordGroups.add(keywordGroupsItem);
    return this;
  }

   /**
   * A group for each type of keyword present
   * @return keywordGroups
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A group for each type of keyword present")

  public List<KeywordGroup> getKeywordGroups() {
    return keywordGroups;
  }


  public void setKeywordGroups(List<KeywordGroup> keywordGroups) {
    this.keywordGroups = keywordGroups;
  }


  public Event links(List<Link> links) {
    
    this.links = links;
    return this;
  }

  public Event addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<Link>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Links to information about the event
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Links to information about the event")

  public List<Link> getLinks() {
    return links;
  }


  public void setLinks(List<Link> links) {
    this.links = links;
  }


  public Event location(String location) {
    
    this.location = location;
    return this;
  }

   /**
   * The actual location of the event
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The actual location of the event")

  public String getLocation() {
    return location;
  }


  public void setLocation(String location) {
    this.location = location;
  }


  public Event organizers(List<OrganizationOrExternalOrganizationRef> organizers) {
    
    this.organizers = organizers;
    return this;
  }

  public Event addOrganizersItem(OrganizationOrExternalOrganizationRef organizersItem) {
    if (this.organizers == null) {
      this.organizers = new ArrayList<OrganizationOrExternalOrganizationRef>();
    }
    this.organizers.add(organizersItem);
    return this;
  }

   /**
   * The organizers of the event
   * @return organizers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The organizers of the event")

  public List<OrganizationOrExternalOrganizationRef> getOrganizers() {
    return organizers;
  }


  public void setOrganizers(List<OrganizationOrExternalOrganizationRef> organizers) {
    this.organizers = organizers;
  }


  public Event lifecycle(DateRange lifecycle) {
    
    this.lifecycle = lifecycle;
    return this;
  }

   /**
   * Get lifecycle
   * @return lifecycle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateRange getLifecycle() {
    return lifecycle;
  }


  public void setLifecycle(DateRange lifecycle) {
    this.lifecycle = lifecycle;
  }


  public Event events(List<EventRef> events) {
    
    this.events = events;
    return this;
  }

  public Event addEventsItem(EventRef eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<EventRef>();
    }
    this.events.add(eventsItem);
    return this;
  }

   /**
   * Other events related to this event
   * @return events
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Other events related to this event")

  public List<EventRef> getEvents() {
    return events;
  }


  public void setEvents(List<EventRef> events) {
    this.events = events;
  }


  public Event identifiers(List<Identifier> identifiers) {
    
    this.identifiers = identifiers;
    return this;
  }

  public Event addIdentifiersItem(Identifier identifiersItem) {
    if (this.identifiers == null) {
      this.identifiers = new ArrayList<Identifier>();
    }
    this.identifiers.add(identifiersItem);
    return this;
  }

   /**
   * IDs that this object corresponds to in external systems. Such as a Scopus ID. Used by Pure where it is necessary to identify objects to specific external systems
   * @return identifiers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "IDs that this object corresponds to in external systems. Such as a Scopus ID. Used by Pure where it is necessary to identify objects to specific external systems")

  public List<Identifier> getIdentifiers() {
    return identifiers;
  }


  public void setIdentifiers(List<Identifier> identifiers) {
    this.identifiers = identifiers;
  }


  public Event sponsorOrganizations(List<OrganizationOrExternalOrganizationRef> sponsorOrganizations) {
    
    this.sponsorOrganizations = sponsorOrganizations;
    return this;
  }

  public Event addSponsorOrganizationsItem(OrganizationOrExternalOrganizationRef sponsorOrganizationsItem) {
    if (this.sponsorOrganizations == null) {
      this.sponsorOrganizations = new ArrayList<OrganizationOrExternalOrganizationRef>();
    }
    this.sponsorOrganizations.add(sponsorOrganizationsItem);
    return this;
  }

   /**
   * The event sponsors
   * @return sponsorOrganizations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The event sponsors")

  public List<OrganizationOrExternalOrganizationRef> getSponsorOrganizations() {
    return sponsorOrganizations;
  }


  public void setSponsorOrganizations(List<OrganizationOrExternalOrganizationRef> sponsorOrganizations) {
    this.sponsorOrganizations = sponsorOrganizations;
  }


  public Event subdivision(ClassificationRef subdivision) {
    
    this.subdivision = subdivision;
    return this;
  }

   /**
   * Get subdivision
   * @return subdivision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ClassificationRef getSubdivision() {
    return subdivision;
  }


  public void setSubdivision(ClassificationRef subdivision) {
    this.subdivision = subdivision;
  }


  public Event title(Map<String, String> title) {
    
    this.title = title;
    return this;
  }

  public Event putTitleItem(String key, String titleItem) {
    if (this.title == null) {
      this.title = new HashMap<String, String>();
    }
    this.title.put(key, titleItem);
    return this;
  }

   /**
   * A set of potentially formatted string values each localized for a specific submission locale. Please note that invalid locale values will be ignored.
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"en_GB\":\"Some text\"}", value = "A set of potentially formatted string values each localized for a specific submission locale. Please note that invalid locale values will be ignored.")

  public Map<String, String> getTitle() {
    return title;
  }


  public void setTitle(Map<String, String> title) {
    this.title = title;
  }


  public Event subTitle(Map<String, String> subTitle) {
    
    this.subTitle = subTitle;
    return this;
  }

  public Event putSubTitleItem(String key, String subTitleItem) {
    if (this.subTitle == null) {
      this.subTitle = new HashMap<String, String>();
    }
    this.subTitle.put(key, subTitleItem);
    return this;
  }

   /**
   * A set of potentially formatted string values each localized for a specific submission locale. Please note that invalid locale values will be ignored.
   * @return subTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"en_GB\":\"Some text\"}", value = "A set of potentially formatted string values each localized for a specific submission locale. Please note that invalid locale values will be ignored.")

  public Map<String, String> getSubTitle() {
    return subTitle;
  }


  public void setSubTitle(Map<String, String> subTitle) {
    this.subTitle = subTitle;
  }


  public Event workflow(Workflow workflow) {
    
    this.workflow = workflow;
    return this;
  }

   /**
   * Get workflow
   * @return workflow
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Workflow getWorkflow() {
    return workflow;
  }


  public void setWorkflow(Workflow workflow) {
    this.workflow = workflow;
  }


   /**
   * The content system name
   * @return systemName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The content system name")

  public String getSystemName() {
    return systemName;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Event event = (Event) o;
    return Objects.equals(this.pureId, event.pureId) &&
        Objects.equals(this.uuid, event.uuid) &&
        Objects.equals(this.createdBy, event.createdBy) &&
        Objects.equals(this.createdDate, event.createdDate) &&
        Objects.equals(this.modifiedBy, event.modifiedBy) &&
        Objects.equals(this.modifiedDate, event.modifiedDate) &&
        Objects.equals(this.portalUrl, event.portalUrl) &&
        Objects.equals(this.prettyUrlIdentifiers, event.prettyUrlIdentifiers) &&
        Objects.equals(this.previousUuids, event.previousUuids) &&
        Objects.equals(this.version, event.version) &&
        Objects.equals(this.type, event.type) &&
        Objects.equals(this.abbreviatedTitle, event.abbreviatedTitle) &&
        Objects.equals(this.geoLocation, event.geoLocation) &&
        Objects.equals(this.city, event.city) &&
        Objects.equals(this.conferenceNumber, event.conferenceNumber) &&
        Objects.equals(this.country, event.country) &&
        Objects.equals(this.degreeOfRecognition, event.degreeOfRecognition) &&
        Objects.equals(this.description, event.description) &&
        Objects.equals(this.keywordGroups, event.keywordGroups) &&
        Objects.equals(this.links, event.links) &&
        Objects.equals(this.location, event.location) &&
        Objects.equals(this.organizers, event.organizers) &&
        Objects.equals(this.lifecycle, event.lifecycle) &&
        Objects.equals(this.events, event.events) &&
        Objects.equals(this.identifiers, event.identifiers) &&
        Objects.equals(this.sponsorOrganizations, event.sponsorOrganizations) &&
        Objects.equals(this.subdivision, event.subdivision) &&
        Objects.equals(this.title, event.title) &&
        Objects.equals(this.subTitle, event.subTitle) &&
        Objects.equals(this.workflow, event.workflow) &&
        Objects.equals(this.systemName, event.systemName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pureId, uuid, createdBy, createdDate, modifiedBy, modifiedDate, portalUrl, prettyUrlIdentifiers, previousUuids, version, type, abbreviatedTitle, geoLocation, city, conferenceNumber, country, degreeOfRecognition, description, keywordGroups, links, location, organizers, lifecycle, events, identifiers, sponsorOrganizations, subdivision, title, subTitle, workflow, systemName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Event {\n");
    sb.append("    pureId: ").append(toIndentedString(pureId)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
    sb.append("    portalUrl: ").append(toIndentedString(portalUrl)).append("\n");
    sb.append("    prettyUrlIdentifiers: ").append(toIndentedString(prettyUrlIdentifiers)).append("\n");
    sb.append("    previousUuids: ").append(toIndentedString(previousUuids)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    abbreviatedTitle: ").append(toIndentedString(abbreviatedTitle)).append("\n");
    sb.append("    geoLocation: ").append(toIndentedString(geoLocation)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    conferenceNumber: ").append(toIndentedString(conferenceNumber)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    degreeOfRecognition: ").append(toIndentedString(degreeOfRecognition)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    keywordGroups: ").append(toIndentedString(keywordGroups)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    organizers: ").append(toIndentedString(organizers)).append("\n");
    sb.append("    lifecycle: ").append(toIndentedString(lifecycle)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("    sponsorOrganizations: ").append(toIndentedString(sponsorOrganizations)).append("\n");
    sb.append("    subdivision: ").append(toIndentedString(subdivision)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    subTitle: ").append(toIndentedString(subTitle)).append("\n");
    sb.append("    workflow: ").append(toIndentedString(workflow)).append("\n");
    sb.append("    systemName: ").append(toIndentedString(systemName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

