/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.model;

import java.util.Objects;
import java.util.Arrays;
import com.elsevier.pure.api.sample.stubs.model.ClassificationRef;
import com.elsevier.pure.api.sample.stubs.model.ClassifiedAddress;
import com.elsevier.pure.api.sample.stubs.model.ClassifiedFile;
import com.elsevier.pure.api.sample.stubs.model.ClassifiedLocalizedValue;
import com.elsevier.pure.api.sample.stubs.model.ClassifiedValue;
import com.elsevier.pure.api.sample.stubs.model.DateRange;
import com.elsevier.pure.api.sample.stubs.model.Identifier;
import com.elsevier.pure.api.sample.stubs.model.KeywordGroup;
import com.elsevier.pure.api.sample.stubs.model.OrganizationRef;
import com.elsevier.pure.api.sample.stubs.model.PersonRef;
import com.elsevier.pure.api.sample.stubs.model.Visibility;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * An organization in the institution
 */
@ApiModel(description = "An organization in the institution")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-21T09:12:55.713+02:00[Europe/Copenhagen]")
public class Organization {
  public static final String SERIALIZED_NAME_PURE_ID = "pureId";
  @SerializedName(SERIALIZED_NAME_PURE_ID)
  private Long pureId;

  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private UUID uuid;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private String createdBy;

  public static final String SERIALIZED_NAME_CREATED_DATE = "createdDate";
  @SerializedName(SERIALIZED_NAME_CREATED_DATE)
  private OffsetDateTime createdDate;

  public static final String SERIALIZED_NAME_MODIFIED_BY = "modifiedBy";
  @SerializedName(SERIALIZED_NAME_MODIFIED_BY)
  private String modifiedBy;

  public static final String SERIALIZED_NAME_MODIFIED_DATE = "modifiedDate";
  @SerializedName(SERIALIZED_NAME_MODIFIED_DATE)
  private OffsetDateTime modifiedDate;

  public static final String SERIALIZED_NAME_PORTAL_URL = "portalUrl";
  @SerializedName(SERIALIZED_NAME_PORTAL_URL)
  private String portalUrl;

  public static final String SERIALIZED_NAME_PRETTY_URL_IDENTIFIERS = "prettyUrlIdentifiers";
  @SerializedName(SERIALIZED_NAME_PRETTY_URL_IDENTIFIERS)
  private List<String> prettyUrlIdentifiers = null;

  public static final String SERIALIZED_NAME_PREVIOUS_UUIDS = "previousUuids";
  @SerializedName(SERIALIZED_NAME_PREVIOUS_UUIDS)
  private List<String> previousUuids = null;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private Map<String, String> name = null;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private ClassificationRef type;

  public static final String SERIALIZED_NAME_IDENTIFIERS = "identifiers";
  @SerializedName(SERIALIZED_NAME_IDENTIFIERS)
  private List<Identifier> identifiers = null;

  public static final String SERIALIZED_NAME_NAME_VARIANTS = "nameVariants";
  @SerializedName(SERIALIZED_NAME_NAME_VARIANTS)
  private List<ClassifiedLocalizedValue> nameVariants = null;

  public static final String SERIALIZED_NAME_PROFILE_INFORMATIONS = "profileInformations";
  @SerializedName(SERIALIZED_NAME_PROFILE_INFORMATIONS)
  private List<ClassifiedLocalizedValue> profileInformations = null;

  public static final String SERIALIZED_NAME_PHOTOS = "photos";
  @SerializedName(SERIALIZED_NAME_PHOTOS)
  private List<ClassifiedFile> photos = null;

  public static final String SERIALIZED_NAME_ADDRESSES = "addresses";
  @SerializedName(SERIALIZED_NAME_ADDRESSES)
  private List<ClassifiedAddress> addresses = null;

  public static final String SERIALIZED_NAME_PHONE_NUMBERS = "phoneNumbers";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBERS)
  private List<ClassifiedValue> phoneNumbers = null;

  public static final String SERIALIZED_NAME_EMAILS = "emails";
  @SerializedName(SERIALIZED_NAME_EMAILS)
  private List<ClassifiedValue> emails = null;

  public static final String SERIALIZED_NAME_WEB_ADDRESSES = "webAddresses";
  @SerializedName(SERIALIZED_NAME_WEB_ADDRESSES)
  private List<ClassifiedLocalizedValue> webAddresses = null;

  public static final String SERIALIZED_NAME_LIFECYCLE = "lifecycle";
  @SerializedName(SERIALIZED_NAME_LIFECYCLE)
  private DateRange lifecycle;

  public static final String SERIALIZED_NAME_TAKEN_OVER_BY = "takenOverBy";
  @SerializedName(SERIALIZED_NAME_TAKEN_OVER_BY)
  private OrganizationRef takenOverBy;

  public static final String SERIALIZED_NAME_PARENTS = "parents";
  @SerializedName(SERIALIZED_NAME_PARENTS)
  private List<OrganizationRef> parents = null;

  public static final String SERIALIZED_NAME_CONTACT_PERSONS = "contactPersons";
  @SerializedName(SERIALIZED_NAME_CONTACT_PERSONS)
  private List<PersonRef> contactPersons = null;

  public static final String SERIALIZED_NAME_KEYWORD_GROUPS = "keywordGroups";
  @SerializedName(SERIALIZED_NAME_KEYWORD_GROUPS)
  private List<KeywordGroup> keywordGroups = null;

  public static final String SERIALIZED_NAME_COST_CENTERS = "costCenters";
  @SerializedName(SERIALIZED_NAME_COST_CENTERS)
  private List<ClassificationRef> costCenters = null;

  public static final String SERIALIZED_NAME_VISIBILITY = "visibility";
  @SerializedName(SERIALIZED_NAME_VISIBILITY)
  private Visibility visibility;

  public static final String SERIALIZED_NAME_SYSTEM_NAME = "systemName";
  @SerializedName(SERIALIZED_NAME_SYSTEM_NAME)
  private String systemName;


   /**
   * Pure database ID of the object, prefer using the UUID if it is present on the entity
   * @return pureId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Pure database ID of the object, prefer using the UUID if it is present on the entity")

  public Long getPureId() {
    return pureId;
  }




   /**
   * UUID, this is the primary identity of the entity
   * @return uuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UUID, this is the primary identity of the entity")

  public UUID getUuid() {
    return uuid;
  }




   /**
   * Username of creator
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Username of creator")

  public String getCreatedBy() {
    return createdBy;
  }




   /**
   * Date and time of creation
   * @return createdDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date and time of creation")

  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }




   /**
   * Username of the user that performed a modification
   * @return modifiedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Username of the user that performed a modification")

  public String getModifiedBy() {
    return modifiedBy;
  }




   /**
   * Date and time of last modification
   * @return modifiedDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date and time of last modification")

  public OffsetDateTime getModifiedDate() {
    return modifiedDate;
  }




   /**
   * URL of the content on the Pure Portal
   * @return portalUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "URL of the content on the Pure Portal")

  public String getPortalUrl() {
    return portalUrl;
  }




   /**
   * All pretty URLs
   * @return prettyUrlIdentifiers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "All pretty URLs")

  public List<String> getPrettyUrlIdentifiers() {
    return prettyUrlIdentifiers;
  }




   /**
   * UUIDs of other content items which have been merged into this content item (or similar)
   * @return previousUuids
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UUIDs of other content items which have been merged into this content item (or similar)")

  public List<String> getPreviousUuids() {
    return previousUuids;
  }




  public Organization version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * A hash representing the current version of the content. For new content this is null, and for existing content the current value. The property should never be modified explicitly by a client.
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A hash representing the current version of the content. For new content this is null, and for existing content the current value. The property should never be modified explicitly by a client.")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public Organization name(Map<String, String> name) {
    
    this.name = name;
    return this;
  }

  public Organization putNameItem(String key, String nameItem) {
    if (this.name == null) {
      this.name = new HashMap<String, String>();
    }
    this.name.put(key, nameItem);
    return this;
  }

   /**
   * A set of string values, one for each submission locale. Note: invalid locale values will be ignored.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"en_GB\":\"Some text\"}", value = "A set of string values, one for each submission locale. Note: invalid locale values will be ignored.")

  public Map<String, String> getName() {
    return name;
  }


  public void setName(Map<String, String> name) {
    this.name = name;
  }


  public Organization type(ClassificationRef type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ClassificationRef getType() {
    return type;
  }


  public void setType(ClassificationRef type) {
    this.type = type;
  }


  public Organization identifiers(List<Identifier> identifiers) {
    
    this.identifiers = identifiers;
    return this;
  }

  public Organization addIdentifiersItem(Identifier identifiersItem) {
    if (this.identifiers == null) {
      this.identifiers = new ArrayList<Identifier>();
    }
    this.identifiers.add(identifiersItem);
    return this;
  }

   /**
   * IDs that this object corresponds to in external systems. Such as a Scopus ID. Used by Pure where it is necessary to identify objects to specific external systems
   * @return identifiers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "IDs that this object corresponds to in external systems. Such as a Scopus ID. Used by Pure where it is necessary to identify objects to specific external systems")

  public List<Identifier> getIdentifiers() {
    return identifiers;
  }


  public void setIdentifiers(List<Identifier> identifiers) {
    this.identifiers = identifiers;
  }


  public Organization nameVariants(List<ClassifiedLocalizedValue> nameVariants) {
    
    this.nameVariants = nameVariants;
    return this;
  }

  public Organization addNameVariantsItem(ClassifiedLocalizedValue nameVariantsItem) {
    if (this.nameVariants == null) {
      this.nameVariants = new ArrayList<ClassifiedLocalizedValue>();
    }
    this.nameVariants.add(nameVariantsItem);
    return this;
  }

   /**
   * A list of organization name variants
   * @return nameVariants
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of organization name variants")

  public List<ClassifiedLocalizedValue> getNameVariants() {
    return nameVariants;
  }


  public void setNameVariants(List<ClassifiedLocalizedValue> nameVariants) {
    this.nameVariants = nameVariants;
  }


  public Organization profileInformations(List<ClassifiedLocalizedValue> profileInformations) {
    
    this.profileInformations = profileInformations;
    return this;
  }

  public Organization addProfileInformationsItem(ClassifiedLocalizedValue profileInformationsItem) {
    if (this.profileInformations == null) {
      this.profileInformations = new ArrayList<ClassifiedLocalizedValue>();
    }
    this.profileInformations.add(profileInformationsItem);
    return this;
  }

   /**
   * A list of organization profile information entries
   * @return profileInformations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of organization profile information entries")

  public List<ClassifiedLocalizedValue> getProfileInformations() {
    return profileInformations;
  }


  public void setProfileInformations(List<ClassifiedLocalizedValue> profileInformations) {
    this.profileInformations = profileInformations;
  }


  public Organization photos(List<ClassifiedFile> photos) {
    
    this.photos = photos;
    return this;
  }

  public Organization addPhotosItem(ClassifiedFile photosItem) {
    if (this.photos == null) {
      this.photos = new ArrayList<ClassifiedFile>();
    }
    this.photos.add(photosItem);
    return this;
  }

   /**
   * A list of organization photos
   * @return photos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of organization photos")

  public List<ClassifiedFile> getPhotos() {
    return photos;
  }


  public void setPhotos(List<ClassifiedFile> photos) {
    this.photos = photos;
  }


  public Organization addresses(List<ClassifiedAddress> addresses) {
    
    this.addresses = addresses;
    return this;
  }

  public Organization addAddressesItem(ClassifiedAddress addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<ClassifiedAddress>();
    }
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * A list of organization addresses
   * @return addresses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of organization addresses")

  public List<ClassifiedAddress> getAddresses() {
    return addresses;
  }


  public void setAddresses(List<ClassifiedAddress> addresses) {
    this.addresses = addresses;
  }


  public Organization phoneNumbers(List<ClassifiedValue> phoneNumbers) {
    
    this.phoneNumbers = phoneNumbers;
    return this;
  }

  public Organization addPhoneNumbersItem(ClassifiedValue phoneNumbersItem) {
    if (this.phoneNumbers == null) {
      this.phoneNumbers = new ArrayList<ClassifiedValue>();
    }
    this.phoneNumbers.add(phoneNumbersItem);
    return this;
  }

   /**
   * A list of organization phone numbers
   * @return phoneNumbers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of organization phone numbers")

  public List<ClassifiedValue> getPhoneNumbers() {
    return phoneNumbers;
  }


  public void setPhoneNumbers(List<ClassifiedValue> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
  }


  public Organization emails(List<ClassifiedValue> emails) {
    
    this.emails = emails;
    return this;
  }

  public Organization addEmailsItem(ClassifiedValue emailsItem) {
    if (this.emails == null) {
      this.emails = new ArrayList<ClassifiedValue>();
    }
    this.emails.add(emailsItem);
    return this;
  }

   /**
   * A list of organization email addresses
   * @return emails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of organization email addresses")

  public List<ClassifiedValue> getEmails() {
    return emails;
  }


  public void setEmails(List<ClassifiedValue> emails) {
    this.emails = emails;
  }


  public Organization webAddresses(List<ClassifiedLocalizedValue> webAddresses) {
    
    this.webAddresses = webAddresses;
    return this;
  }

  public Organization addWebAddressesItem(ClassifiedLocalizedValue webAddressesItem) {
    if (this.webAddresses == null) {
      this.webAddresses = new ArrayList<ClassifiedLocalizedValue>();
    }
    this.webAddresses.add(webAddressesItem);
    return this;
  }

   /**
   * A list of organization web addresses
   * @return webAddresses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of organization web addresses")

  public List<ClassifiedLocalizedValue> getWebAddresses() {
    return webAddresses;
  }


  public void setWebAddresses(List<ClassifiedLocalizedValue> webAddresses) {
    this.webAddresses = webAddresses;
  }


  public Organization lifecycle(DateRange lifecycle) {
    
    this.lifecycle = lifecycle;
    return this;
  }

   /**
   * Get lifecycle
   * @return lifecycle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateRange getLifecycle() {
    return lifecycle;
  }


  public void setLifecycle(DateRange lifecycle) {
    this.lifecycle = lifecycle;
  }


  public Organization takenOverBy(OrganizationRef takenOverBy) {
    
    this.takenOverBy = takenOverBy;
    return this;
  }

   /**
   * Get takenOverBy
   * @return takenOverBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OrganizationRef getTakenOverBy() {
    return takenOverBy;
  }


  public void setTakenOverBy(OrganizationRef takenOverBy) {
    this.takenOverBy = takenOverBy;
  }


  public Organization parents(List<OrganizationRef> parents) {
    
    this.parents = parents;
    return this;
  }

  public Organization addParentsItem(OrganizationRef parentsItem) {
    if (this.parents == null) {
      this.parents = new ArrayList<OrganizationRef>();
    }
    this.parents.add(parentsItem);
    return this;
  }

   /**
   * A list of parent organizations
   * @return parents
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of parent organizations")

  public List<OrganizationRef> getParents() {
    return parents;
  }


  public void setParents(List<OrganizationRef> parents) {
    this.parents = parents;
  }


  public Organization contactPersons(List<PersonRef> contactPersons) {
    
    this.contactPersons = contactPersons;
    return this;
  }

  public Organization addContactPersonsItem(PersonRef contactPersonsItem) {
    if (this.contactPersons == null) {
      this.contactPersons = new ArrayList<PersonRef>();
    }
    this.contactPersons.add(contactPersonsItem);
    return this;
  }

   /**
   * A list of organization contact persons
   * @return contactPersons
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of organization contact persons")

  public List<PersonRef> getContactPersons() {
    return contactPersons;
  }


  public void setContactPersons(List<PersonRef> contactPersons) {
    this.contactPersons = contactPersons;
  }


  public Organization keywordGroups(List<KeywordGroup> keywordGroups) {
    
    this.keywordGroups = keywordGroups;
    return this;
  }

  public Organization addKeywordGroupsItem(KeywordGroup keywordGroupsItem) {
    if (this.keywordGroups == null) {
      this.keywordGroups = new ArrayList<KeywordGroup>();
    }
    this.keywordGroups.add(keywordGroupsItem);
    return this;
  }

   /**
   * A group for each type of keyword present
   * @return keywordGroups
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A group for each type of keyword present")

  public List<KeywordGroup> getKeywordGroups() {
    return keywordGroups;
  }


  public void setKeywordGroups(List<KeywordGroup> keywordGroups) {
    this.keywordGroups = keywordGroups;
  }


  public Organization costCenters(List<ClassificationRef> costCenters) {
    
    this.costCenters = costCenters;
    return this;
  }

  public Organization addCostCentersItem(ClassificationRef costCentersItem) {
    if (this.costCenters == null) {
      this.costCenters = new ArrayList<ClassificationRef>();
    }
    this.costCenters.add(costCentersItem);
    return this;
  }

   /**
   * A list of cost center classifications
   * @return costCenters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of cost center classifications")

  public List<ClassificationRef> getCostCenters() {
    return costCenters;
  }


  public void setCostCenters(List<ClassificationRef> costCenters) {
    this.costCenters = costCenters;
  }


  public Organization visibility(Visibility visibility) {
    
    this.visibility = visibility;
    return this;
  }

   /**
   * Get visibility
   * @return visibility
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Visibility getVisibility() {
    return visibility;
  }


  public void setVisibility(Visibility visibility) {
    this.visibility = visibility;
  }


   /**
   * The content system name
   * @return systemName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The content system name")

  public String getSystemName() {
    return systemName;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Organization organization = (Organization) o;
    return Objects.equals(this.pureId, organization.pureId) &&
        Objects.equals(this.uuid, organization.uuid) &&
        Objects.equals(this.createdBy, organization.createdBy) &&
        Objects.equals(this.createdDate, organization.createdDate) &&
        Objects.equals(this.modifiedBy, organization.modifiedBy) &&
        Objects.equals(this.modifiedDate, organization.modifiedDate) &&
        Objects.equals(this.portalUrl, organization.portalUrl) &&
        Objects.equals(this.prettyUrlIdentifiers, organization.prettyUrlIdentifiers) &&
        Objects.equals(this.previousUuids, organization.previousUuids) &&
        Objects.equals(this.version, organization.version) &&
        Objects.equals(this.name, organization.name) &&
        Objects.equals(this.type, organization.type) &&
        Objects.equals(this.identifiers, organization.identifiers) &&
        Objects.equals(this.nameVariants, organization.nameVariants) &&
        Objects.equals(this.profileInformations, organization.profileInformations) &&
        Objects.equals(this.photos, organization.photos) &&
        Objects.equals(this.addresses, organization.addresses) &&
        Objects.equals(this.phoneNumbers, organization.phoneNumbers) &&
        Objects.equals(this.emails, organization.emails) &&
        Objects.equals(this.webAddresses, organization.webAddresses) &&
        Objects.equals(this.lifecycle, organization.lifecycle) &&
        Objects.equals(this.takenOverBy, organization.takenOverBy) &&
        Objects.equals(this.parents, organization.parents) &&
        Objects.equals(this.contactPersons, organization.contactPersons) &&
        Objects.equals(this.keywordGroups, organization.keywordGroups) &&
        Objects.equals(this.costCenters, organization.costCenters) &&
        Objects.equals(this.visibility, organization.visibility) &&
        Objects.equals(this.systemName, organization.systemName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pureId, uuid, createdBy, createdDate, modifiedBy, modifiedDate, portalUrl, prettyUrlIdentifiers, previousUuids, version, name, type, identifiers, nameVariants, profileInformations, photos, addresses, phoneNumbers, emails, webAddresses, lifecycle, takenOverBy, parents, contactPersons, keywordGroups, costCenters, visibility, systemName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Organization {\n");
    sb.append("    pureId: ").append(toIndentedString(pureId)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
    sb.append("    portalUrl: ").append(toIndentedString(portalUrl)).append("\n");
    sb.append("    prettyUrlIdentifiers: ").append(toIndentedString(prettyUrlIdentifiers)).append("\n");
    sb.append("    previousUuids: ").append(toIndentedString(previousUuids)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("    nameVariants: ").append(toIndentedString(nameVariants)).append("\n");
    sb.append("    profileInformations: ").append(toIndentedString(profileInformations)).append("\n");
    sb.append("    photos: ").append(toIndentedString(photos)).append("\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    phoneNumbers: ").append(toIndentedString(phoneNumbers)).append("\n");
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("    webAddresses: ").append(toIndentedString(webAddresses)).append("\n");
    sb.append("    lifecycle: ").append(toIndentedString(lifecycle)).append("\n");
    sb.append("    takenOverBy: ").append(toIndentedString(takenOverBy)).append("\n");
    sb.append("    parents: ").append(toIndentedString(parents)).append("\n");
    sb.append("    contactPersons: ").append(toIndentedString(contactPersons)).append("\n");
    sb.append("    keywordGroups: ").append(toIndentedString(keywordGroups)).append("\n");
    sb.append("    costCenters: ").append(toIndentedString(costCenters)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    systemName: ").append(toIndentedString(systemName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

