/*
 * Pure API
 * This is an early access version of the new Pure write API.
 *
 * The version of the OpenAPI document: 0.1 Early Access
 * Contact: b.plauborg@elsevier.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.elsevier.pure.api.sample.stubs.api;

import com.elsevier.pure.api.sample.stubs.invoker.ApiException;
import com.elsevier.pure.api.sample.stubs.model.AuditEntriesQuery;
import com.elsevier.pure.api.sample.stubs.model.AuditEntryListResult;
import com.elsevier.pure.api.sample.stubs.model.ProblemDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuditEntryApi
 */
@Ignore
public class AuditEntryApiTest {

    private final AuditEntryApi api = new AuditEntryApi();

    
    /**
     * Query operation for audit entries
     *
     * Lists audit entries in the Pure instance that matches the provided query, similar to the GET version, instead of using parameters to alter the response, an JSON document is posted with the request. The JSON document contains fields for all the parameters available for the GET version, but also additional filtering options.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryTest() throws ApiException {
        AuditEntriesQuery auditEntriesQuery = null;
        AuditEntryListResult response = api.query(auditEntriesQuery);

        // TODO: test validations
    }
    
}
